services:
  - type: web
    name: groq-api-server-rust
    env: rust
    region: oregon # या मुंबई: asia-south1 (optional)
    plan: free
    buildCommand: "cargo build --release"
    startCommand: "./target/release/groq-api-server"
    envVars:
      - key: GROQ_API_KEY
        sync: false
